from django.core.management.base import BaseCommand
from django.db import transaction

from members.models import Organisation


class Command(BaseCommand):
    help = 'Does some very user specific data input from what was previously a spreadsheet'

    def save_or_locate(self, the_obj):
        '''
        A method generated by a "script the data" feature
        of Django Extras and which I've reused here
        '''
        try:
            the_obj.save()
        except:
            print("---------------")
            print("Error saving the following object:")
            print(the_obj.__class__)
            print(" ")
            print(the_obj.__dict__)
            print(" ")
            print(the_obj)
            print(" ")
            print("---------------")

            raise
        return the_obj

    def handle(self, *args, **options):
        do_rollback = True
        self.stdout.write('About to start conversion')
        with transaction.atomic():
            sid = transaction.savepoint()
            members_organisation_1 = Organisation()
            members_organisation_1.name = u'Conversion Group'
            members_organisation_1 = self.save_or_locate(members_organisation_1)
            if do_rollback:
                transaction.savepoint_rollback(sid)
            else:
                transaction.savepoint_commit(sid)
            self.stdout.write('Org Name =  "%s"' % members_organisation_1.name)
